In [45]:
import numpy as np
import math

In [46]:
n=5
m=15
w = [12, 2, 1, 1, 4]
v = [4, 2, 1, 2, 10]

dvar = [0 ,1 ,1, 0, 1]

In [47]:
class DNA:
    def __init__(self, dv=[]):
        if len(dv)==0:
            self.dvar = np.random.randint(0,2,n)
        else:
            self.dvar = dv
        self.fitness = None
        self.total_weight = None

    def calc_fitness(self):
        self.fitness = np.sum(self.dvar * np.array(v))
        self.total_weight = np.sum(self.dvar * np.array(w))
        if self.total_weight>m:
            violate = self.total_weight-m
            self.fitness = self.fitness - 4*violate
    
    def mutate(self):
        for i in range(n):
            if np.random.rand()<0.2:
                self.dvar[i] = 1-self.dvar[i]



In [48]:
def crossover(dna1, dna2):
    mid = np.random.randint(0,n)
    new_dna = DNA(dv=np.concatenate([dna1.dvar[0:mid], dna2.dvar[mid:n]]))
    return new_dna

In [49]:
abc = DNA()
abc.calc_fitness()
print(abc.dvar)
print(abc.fitness)
print(abc.total_weight)

[0 0 1 0 1]
11
5


In [50]:
def fitness_curve(fit):
    return (1/2)* pow(fit,2)

In [51]:
fitness_curve(2)

2.0

In [52]:
# init population
pop_size = 20
population = []
for i in range(pop_size):
    population.append(DNA())
    population[i].calc_fitness()

In [53]:
import math
pool = []
for i in range(pop_size):
    for j in range(math.floor(fitness_curve(population[i].fitness))):
        pool.append(i)

In [54]:
print(pool)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 

In [55]:
print(population[0].dvar)
print(population[2].dvar)

[0 0 0 0 1]
[1 1 0 0 0]


In [56]:
num_of_it = 100
# best_dna = DNA()
best_fitness = -10000

for it in range(num_of_it):
    print("Iteration", it)
    new_population = []
    pool = []
    for i in range(pop_size):
        print(population[i].fitness)
        for j in range(math.floor(fitness_curve(population[i].fitness))):
            pool.append(i)
    for i in range(pop_size):
        id1 = np.random.choice(pool)
        id2 = np.random.choice(pool)
        new_dna = crossover(population[id1], population[id2])
        new_dna.mutate()
        new_dna.calc_fitness()
        if new_dna.fitness > best_fitness:
            best_fitness = new_dna.fitness
            best_dna = new_dna
            print(best_fitness)
        new_population.append(new_dna)
    population = new_population
    
best_dna.calc_fitness()
print(best_dna.fitness)
print(best_dna.dvar)

Iteration 0
10
12
6
3
7
10
8
10
4
10
5
5
7
7
1
4
11
8
12
7
5
10
12
Iteration 1
5
0
10
10
8
10
8
7
10
4
12
8
1
12
12
5
7
2
10
8
13
15
Iteration 2
8
8
13
10
8
0
10
11
15
5
2
8
15
6
10
7
2
13
12
4
Iteration 3
8
8
12
15
10
14
0
10
12
15
13
8
13
10
5
3
5
7
4
8
Iteration 4
4
13
4
2
1
5
10
2
12
5
2
5
12
10
11
12
7
14
15
14
Iteration 5
13
10
3
1
8
12
11
14
12
11
8
8
11
15
8
4
3
7
11
12
Iteration 6
14
15
13
1
13
5
12
11
12
5
7
12
15
13
4
8
11
13
12
-1
Iteration 7
12
2
2
14
13
13
1
15
4
12
3
11
11
15
13
12
1
11
0
11
Iteration 8
15
2
13
2
13
7
3
14
10
12
2
13
11
2
-1
12
13
2
14
15
Iteration 9
15
0
13
15
12
13
6
2
3
13
11
11
11
12
14
-1
10
2
15
2
Iteration 10
13
4
13
4
5
12
15
14
5
13
15
1
4
12
13
13
13
4
15
11
Iteration 11
0
1
5
12
13
11
15
12
8
10
15
13
1
5
15
11
4
5
15
12
Iteration 12
13
12
0
6
2
13
10
12
11
3
13
4
3
13
12
14
15
-1
6
15
Iteration 13
13
8
10
-1
-1
3
5
10
12
12
6
10
11
15
3
14
2
12
12
12
Iteration 14
8
0
2
10
2
7
2
12
12
15
2
10
14
12
3
12
14
14
13
14
Iteration 15
2
15
2
11
0
15
